### ISSUE TITLE
SRSRAN last version merge 

### ISSUE THREAD

**Issue by reshmem** [kotuliak/dlProbe#1]
Hello, 

Nice to meet you. I try to bring support for 5g in to DLProbe, and have a question. It will be really helpful to know exact commit that you forked from `srsran` library. Any chance you can find it somehow ? 

Best.

**Comment by kotuliak** [comment]
Hi,

it's based on the Release 21.10; so commit: https://github.com/srsran/srsRAN/commit/5275f33360f1b3f1ee8d1c4d9ae951ac7c4ecd4e

Best,
Martin

**Comment by reshmem** [comment]
Thank you ! :)
