### ISSUE TITLE
Intepretation TMSI in output

### ISSUE THREAD

**Issue by koh-osug** [kotuliak/dlProbe#2]
When running the tool the TMSI is often printed on the console. Is this TMSI the TMSI of the UE simulated using the SDR or is this a TMSI from other devices? How can it be differentiated?

**Comment by kotuliak** [comment]
The printed TMSIs are TMSIs of other users connecting to the cell. If the UE sends a TMSI inside the RRC Connection Request message, it will be printed by our tool. Our tool by itself does not have a TMSI since it is completely passive.
