### ISSUE TITLE
Downlink

### ISSUE THREAD

**Issue by flyguy999999** [kotuliak/dlProbe#4]
Running this software, question, are the UE simulated, and this program completely passive? and is this a version of the DLProbe from your paper?

**Comment by kotuliak** [comment]
Hi, simulated UEs is a bit misleading name unfortunately. It spawns UE stacks every time there is a new connection and number of simulated UEs means how many stack it can use at a given time. It only receives samples, so it is completely passive.

Yes, this is essentially the same as DL probe in our paper. It has some additional capabilities though.

**Comment by flyguy999999** [comment]
That clears up a lot of the questions, I had as I was looking through this, thank you for your response. As for the additional capabilities, is this referring to the ability to obtain the TA (which is this TA from UE to sniffer or to the eNobeB? Again thanks for answering my questions!

**Comment by kotuliak** [comment]
No, it can only get TA inside the RAR. The extra capability is a live decoder of higher layers on the DL. You dont need to post-process the DL messages anymore.

**Comment by flyguy999999** [comment]
Thank you so much. I guess my final question after mesing around wit hthis, is there any way to include the paging traffic in the pcaps?

**Comment by kotuliak** [comment]
this is not implemented right now. You should be able to get this functionality quite easily with srsUE.
